services:
  postgres:
    image: postgres:15
    container_name: control_plane_db
    restart: always
    environment:
      POSTGRES_USER: aryamansondhi
      POSTGRES_PASSWORD: A61shivalik
      POSTGRES_DB: control_plane
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
